name: 生成自定义xray服务器镜像
on:
  push:
    branches:
      - 'server'
jobs:
  job:
    name: 构建镜像
    runs-on: ubuntu-20.04
    steps:
      - name: checkout出xray-parser项目
        uses: actions/checkout@v3.5.2
        with:
          repository: nichuanfang/xray-parser
          path: xray-parser
          ref: server
          token: ${{ secrets.GH_TOKEN }}

      - name: checkout出docker项目
        uses: actions/checkout@v3.5.2
        with:
          repository: nichuanfang/docker
          path: docker
          ref: master
          token: ${{ secrets.GH_TOKEN }}

      - name: xray-parser=>docker
        run: mv $GITHUB_WORKSPACE/xray-parser $GITHUB_WORKSPACE/docker/dockerfile_work/xray

      - name: 构建xray服务端镜像
        run: |
          # 构建镜像
          docker build -t registry.cn-hangzhou.aliyuncs.com/jayzhou/xray:latest \
            --build-arg XRAY_VERSION=${{ vars.XRAY_VERSION }} \
            --build-arg XRAY_WINDOWS_KEY=${{ secrets.XRAY_WINDOWS_KEY }} \
            --build-arg XRAY_TROJAN_KEY=${{ secrets.XRAY_TROJAN_KEY }} \
            $GITHUB_WORKSPACE/docker/dockerfile_work/xray
          # 消息通知密钥信息
          curl -L https://api.day.app/${{ secrets.BARK_TOKEN }}/xray-windows密钥/${{ secrets.XRAY_WINDOWS_KEY }}
          curl -L https://api.day.app/${{ secrets.BARK_TOKEN }}/xray-trojan密钥/${{ secrets.XRAY_TROJAN_KEY }}

      - name: 推送镜像
        run: |
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.ALI_DOCKER_USERNAME }} --password=${{ secrets.ALI_DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 推送镜像
          docker push registry.cn-hangzhou.aliyuncs.com/jayzhou/xray:latest
          # 移除本地镜像
          docker rmi -f registry.cn-hangzhou.aliyuncs.com/jayzhou/xray:latest
          # 发送Bark推送
          curl -L https://api.day.app/${{ secrets.BARK_TOKEN }}/xray镜像已更新

      - name: 启动服务
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing something after copying'
        with:
          host: ${{ secrets.DC_HOST }}
          user: ${{ secrets.DC_USER }}
          pass: ${{ secrets.DC_PASS }}
          port: ${{ secrets.DC_PORT }}
          connect_timeout: 10s
          first_ssh: |
            apt-get install docker.io -y
            apt-get install docker-compose -y
          scp: |
            './docker/dockerfile_work/xray/docker-compose.yml' => /root/
          last_ssh: |
            docker-compose -f /root/docker-compose.yml down
            docker-compose -f /root/docker-compose.yml pull
            docker-compose -f /root/docker-compose.yml up -d
            curl -L https://api.day.app/${{ secrets.BARK_TOKEN }}/xray服务已启动