# 在目标服务器定期生成证书并提交到docker库中
name: renew-cert

# https://docs.github.com/cn/actions/reference/events-that-trigger-workflows#workflow_dispatch
on:
  # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  # 定时任务
  push:
    branches:
      - 'server'
jobs:
  trigger:
    name: 生成证书
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
