# 在目标服务器定期生成证书并提交到docker库中
name: renew-cert
on:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  trigger:
    name: 生成证书
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
