# 注: 定时任务的yml只有放在主分支上面才生效!
name: Renew Xray Cert
on:
  # 手动触发 相关文档 https://docs.github.com/cn/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
          - client
          - server

  schedule:
    - cron: '0 5 * * *'
jobs:
  refresh-cert:
    name: 刷新证书
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
