name: 同步环境变量
on:
  # 手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: '创建xray服务器时执行该同步'
        required: false
        default: 'warning'
      tags:
        description: 'update config-server'

jobs:
  job1:
    name: 同步环境变量
    runs-on: ubuntu-20.04
    steps:
      - name: 更新nichuanfang/config-server的VPS_HOST
        uses: jon-grey/github-actions-secrets-creator@v1
        with:
          location: nichuanfang/config-server
          name: VPS_HOST
          value: ${{ secrets.VPS_HOST }}
          pa_token: ${{ secrets.GH_TOKEN }}

      - name: 更新nichuanfang/config-server的VPS_HOST_NAME
        uses: jon-grey/github-actions-secrets-creator@v1
        with:
          location: nichuanfang/config-server
          name: VPS_HOST_NAME
          value: ${{ secrets.VPS_DOMAIN }}
          pa_token: ${{ secrets.GH_TOKEN }}

      - name: 更新nichuanfang/config-server的VPS_USER
        uses: jon-grey/github-actions-secrets-creator@v1
        with:
          location: nichuanfang/config-server
          name: VPS_USER
          value: ${{ secrets.VPS_USER }}
          pa_token: ${{ secrets.GH_TOKEN }}

      - name: 更新nichuanfang/config-server的VPS_PORT
        uses: jon-grey/github-actions-secrets-creator@v1
        with:
          location: nichuanfang/config-server
          name: VPS_PORT
          value: ${{ secrets.VPS_PORT }}
          pa_token: ${{ secrets.GH_TOKEN }}

      - name: 更新nichuanfang/config-server的VPS_PASS
        uses: jon-grey/github-actions-secrets-creator@v1
        with:
          location: nichuanfang/config-server
          name: VPS_PASS
          value: ${{ secrets.VPS_PASS }}
          pa_token: ${{ secrets.GH_TOKEN }}
